// AUTO-GENERATED by scripts/generate-articles-data.mjs
// Do not edit manually. Update memory/content/published/* and re-run generation.

export interface Article {
  slug: string
  title: string
  subtitle: string
  date: string
  dateFormatted: string
  category: string
  tags: string[]
  readingTime: string
  excerpt: string
  content: string
  linkedinUrl: string
  author: string
  authorBio: string
  featured: boolean
  heroImage?: string
}

export const articles: Article[] = [
  {
    slug: "ai-governance-cybersecurity",
    title: "AI Governance Starts as Cybersecurity Governance",
    subtitle: "Why effective AI oversight builds on existing cybersecurity frameworks",
    date: "2026-03-25",
    dateFormatted: "March 25, 2026",
    category: "AI Governance",
    tags: ["Ai governance","Cybersecurity","Board governance","Eu ai act","Ciso","Risk management"],
    readingTime: "7 min read",
    featured: false,
    heroImage: "/images/articles/ai-governance-cybersecurity.svg",
    linkedinUrl: "",
    author: "Arnaud Wiehe",
    authorBio: "Author of 'Emerging Tech, Emerging Threats' and 'AI Governance Guide'. Building AI governance frameworks for enterprise.",
    excerpt: "The good news is that effective AI governance does not require inventing entirely new frameworks. Organizations that have built robust cybersecurity governance already have the foundation. The challenge is extending those structures to address AI's unique risks.",
    content: `
<p>&gt; "If a machine is expected to be infallible, it cannot also be intelligent." &gt; -- Alan Turing, pioneer in computer science and artificial intelligence</p>

<p>In March 2016, DeepMind's AlphaGo defeated Lee Sedol, one of the world's top Go players, in a match that captured global attention. The ancient game of Go, known for its strategic depth and astronomical number of possible moves, had been considered beyond the reach of artificial intelligence. AlphaGo's victory demonstrated something profound: AI could handle tasks requiring not just calculation, but creativity and intuition.</p>

<p>That was over a decade ago. Since then, the pace of AI development has only accelerated. The launch of ChatGPT in November 2022 brought generative AI into mainstream consciousness. Within months, organizations were racing to deploy AI systems for everything from customer service to content creation to code generation. Google responded with Gemini. Meta released Llama 2 as an open-source model. Anthropic introduced Claude. The competitive pressure to adopt AI became intense.</p>

<p>But here is what many organizations discovered: the governance structures that protect traditional IT systems are woefully inadequate for AI. AI systems do not behave like traditional software. They learn, adapt, and make decisions in ways that can be opaque even to their creators. The data that powers them, the training data, has become the new crown jewels, requiring protection that goes far beyond traditional data security.</p>

<p>The good news is that effective AI governance does not require inventing entirely new frameworks. Organizations that have built robust cybersecurity governance already have the foundation. The challenge is extending those structures to address AI's unique risks.</p>

<h2>The Governance Foundation Already Exists</h2>

<p>In my previous book, The Book on Cybersecurity, I outlined five questions every board should ask about cybersecurity:</p>

<p>1. What is our current cybersecurity posture? 2. What are our biggest cybersecurity risks? 3. How much are we spending and is it sufficient? 4. Do we have a tested incident response plan? 5. Are we compliant with evolving regulations?</p>

<p>These same five questions apply directly to AI governance. The CISO who manages cybersecurity risk can extend that oversight to AI systems. The governance committees that oversee technology and risk can add AI to their mandates. The incident response plans that cover data breaches can be adapted for AI failures.</p>

<p>The key insight is this that AI governance is not a separate discipline requiring separate committees, separate budgets, and separate reporting lines. It is an extension of cybersecurity governance into a new domain.</p>

<h2>Why AI Security Is Different</h2>

<p>While the governance structures remain the same, the technical risks differ significantly. Traditional cybersecurity focuses on protecting data at rest and in transit. AI security must protect training data integrity, model behavior, and output safety.</p>

<p>Consider data poisoning. In a traditional system, corrupted data might cause a database error or produce incorrect reports. In an AI system, poisoned training data can cause the model to learn wrong patterns and these patterns can persist and compound over time. The model might systematically discriminate against certain groups, generate harmful content, or make unsafe recommendations.</p>

<p>Microsoft learned this lesson with Tay, its Twitter chatbot released in 2016. Within hours of launch, malicious actors fed Tay a stream of harmful content. The bot learned from these interactions and began generating offensive tweets. Microsoft swiftly withdraw the bot.</p>

<p>The Tay incident illustrates a fundamental difference, that AI systems learn continuously from their environment. Traditional software does not change its behavior based on user inputs unless explicitly programmed to do so. AI systems do, making them both more powerful and more vulnerable.</p>

<h2>The New Crown Jewels, Training Data</h2>

<p>In traditional cybersecurity, we identify crown jewels, the data assets most critical to the organization, and apply strongest protection. Customer databases. Financial records. Intellectual property.</p>

<p>For AI governance, training data becomes the crown jewels. The quality, integrity, and security of training data directly determines model behavior. Yet many organizations have been shockingly cavalier about training data protection.</p>

<p>The risks extend beyond confidentiality. Training data integrity matters as much as secrecy. If attackers can manipulate training data, even subtly, they can influence model behavior in ways that may be difficult to detect. A financial institution's lending model trained on poisoned data might systematically discriminate against certain applicants. A medical diagnostic AI trained on corrupted images might misclassify diseases.</p>

<p>Organizations must apply the same rigor to training data protection that they apply to their most sensitive databases:</p>

<ul><li>Data validation and cleaning: Rigorous quality control, outlier detection, and anomaly identification before data enters the training pipeline</li><li>Source verification: Risk analysis on every data input, with particular scrutiny on external data sources</li><li>Access controls: Limiting who can modify training data and maintaining audit trails of all changes</li><li>Version control: Tracking which data versions trained which model versions, enabling rollback if problems emerge</li></ul>

<h2>Extending the CISO's Role</h2>

<p>The Chief Information Security Officer is already responsible for identifying and managing cybersecurity risks across the organization. AI risk should fall naturally within this mandate.</p>

<p>The CISO understands the organization's risk appetite. They have established relationships with the board and executive leadership. They have built incident response capabilities. They have navigated compliance requirements. These same capabilities apply to AI risk.</p>

<p>However, the CISO will need additional expertise. Understanding model behavior, recognizing training data poisoning, and evaluating AI-specific threats requires skills that traditional cybersecurity training may not cover. Organizations should invest in upskilling their security teams or bringing in AI security specialists who can work within existing governance structures.</p>

<p>The alternative, creating a separate "Chief AI Officer" with independent reporting lines and separate governance, but risks fragmentation. The CISO manages digital risk. AI is digital risk. The governance should reflect this continuity.</p>

<h2>Practical AI Governance Steps</h2>

<p>For organizations beginning their AI governance journey, here are practical steps that leverage existing cybersecurity infrastructure:</p>

<p>1. Inventory AI Systems: Just as you inventory IT assets, you should also inventory AI systems. What models are in production? What data do they use? Who is responsible for their operation? This inventory should live within existing asset management processes, not in a separate silo.</p>

<p>2. Extend Risk Assessment Frameworks: The risk assessment frameworks that evaluate traditional IT systems can evaluate AI systems, but the threat model must expand. Consider adversarial attacks designed to fool models. Consider data leakage through model outputs. Consider supply chain risks in pre-trained models obtained from third parties.</p>

<p>3. Apply Secure Development Practices: The secure software development lifecycle applies to AI systems. Code review. Testing. Staging environments. Rollback capabilities. These practices should govern how AI systems move from development to production.</p>

<p>4. Monitor Model Behavior: Traditional systems are monitored for availability and performance. AI systems need additional monitoring, for output quality, for drift in behavior, for signs of adversarial manipulation. Build these capabilities into existing monitoring infrastructure.</p>

<p>5. Prepare for AI-Specific Incidents: Incident response plans should include AI-specific scenarios. What happens when a model starts generating harmful content? When training data is discovered to be poisoned? When a model's outputs violate regulations? Run tabletop exercises that include these scenarios.</p>

<h2>The Regulatory Context</h2>

<p>AI governance is not just about managing risk, it is also becoming a regulatory requirement. The European Union's AI Act, which entered into force in August 2024, establishes risk-based obligations for AI systems. High-risk AI systems, including those used in critical infrastructure, employment, and law enforcement, face stringent requirements for risk management, data governance, and human oversight.</p>

<p>Organizations subject to NIS2, DORA, and sectoral regulations are finding that AI systems fall within scope. The governance structures built for cybersecurity compliance must expand to cover AI compliance.</p>

<p>The key is integration, not duplication. The compliance officer tracking cybersecurity requirements should track AI requirements in the same system. The audit committee reviewing cybersecurity controls should review AI controls using similar frameworks.</p>

<h2>Building a Culture of Responsible AI</h2>

<p>Ultimately, governance structures succeed or fail based on organizational culture. The same cultural elements that support strong cybersecurity like commitment from leadership, obsession with prevention, collaboration across departments, willingness to learn from mistakes, also apply to AI.</p>

<p>When boards treat AI governance as a technical matter to be delegated, they create blind spots. When they engage actively, ask probing questions, and hold management accountable, they signal that responsible AI is everyone's responsibility.</p>

<p>The organizations that will thrive in the AI era are not those that deploy the most AI fastest. They are those that deploy AI responsibly, with governance structures that ensure systems behave safely, securely, and ethically.</p>

<p>Those governance structures already exist in well-run organizations. They are called cybersecurity governance. Extend them to cover AI, and you have the foundation for responsible AI deployment.</p>

<p><em>Published March 25, 2026 | Draws from "The Book on Cybersecurity" (2023) and "Emerging Tech, Emerging Threats" (2024)</em></p>
    `,
  },
  {
    slug: "boards-cyber-agenda-2026",
    title: "The Board's Cyber Agenda Has Changed: What Directors Need to Ask in 2026",
    subtitle: "Five questions every board should be asking about cybersecurity governance",
    date: "2026-03-25",
    dateFormatted: "March 25, 2026",
    category: "Board Governance",
    tags: ["Board governance","Cybersecurity","Nis2","Dora","Sec disclosure","Risk management"],
    readingTime: "8 min read",
    featured: true,
    heroImage: "/images/articles/boards-cyber-agenda-2026.svg",
    linkedinUrl: "",
    author: "Arnaud Wiehe",
    authorBio: "Author of 'The Book on Cybersecurity' and 'Emerging Tech, Emerging Threats'. Advisor to boards on digital risk.",
    excerpt: "Something fundamental shifted in how boards must approach cybersecurity. Directors are now expected to understand cyber as a business resilience issue, a fiduciary responsibility, and increasingly, a personal liability concern. Here are the five questions that should now be standard in every boardroom.",
    content: `
<p>&gt; "Boards are now retaining third-party technology expert-futurists, cyber risk experts, inventors--to make sure the board is kept updated and has access to outside perspective to help validate what they hear from management." &gt; -- Dr. Richard LeBlanc, Professor of Governance, Law and Ethics</p>

<p>Something fundamental shifted in how boards must approach cybersecurity. It is no longer enough to hear a quarterly update from the Chief Information Security Officer and move on. Directors are now expected to understand cyber as a business resilience issue, a fiduciary responsibility, and increasingly, a personal liability concern.</p>

<p>The warning signs have been building for years. In October 2022, the U.S. Federal Trade Commission announced a settlement with alcohol delivery service Drizly and its CEO over a data breach affecting 2.5 million consumers. The agency required the company to implement a data security program--and bound the CEO personally to security requirements in future roles. Sanctioning the CEO personally was unusual, and it signaled something important: regulators would no longer treat cybersecurity failures as purely organizational problems.</p>

<p>Since then, the stakes have only risen. The European Union's NIS2 Directive, now being transposed into national law across member states, explicitly holds board members accountable for cybersecurity governance failures. In the United States, the Securities and Exchange Commission's 2023 disclosure rules require public companies to report material cybersecurity incidents within four days--and to describe their board's oversight processes. The Digital Operational Resilience Act (DORA) now imposes similar accountability on financial entities and their technology service providers.</p>

<p>What does this mean for directors in practice? It means the questions you ask, the expertise you access, and the rigor you apply to cybersecurity oversight must evolve. Here are the questions that should now be standard in every boardroom.</p>

<h2>1. What Is Our Current Cybersecurity Posture, and How Mature Is Our Function?</h2>

<p>This question sounds basic, but it remains the foundation of effective oversight. You need to understand not just what security controls exist, but whether they are proportionate to your organization's risk profile.</p>

<p>Ask your CISO for an honest assessment of the cybersecurity function's maturity. Is it reactive, responding to incidents as they occur? Or is it proactive, anticipating threats and building resilience before problems arise? Understanding the staffing structure, how many security professionals per thousand employees, how the function is funded, whether it can attract and retain talent, gives you critical context.</p>

<p>The CISO's role has become one of the most demanding in the executive suite. According to research by Nominet, the average tenure of a CISO is just 26 months. A quarter of CISOs surveyed reported that their boards did not accept that breaches were inevitable, and that boards would hold them personally accountable for incidents. This is unsustainable. When your CISO asks for resources, additional headcount, training budget, technology investments, assume they are asking in good faith. Underinvesting in cybersecurity is a false economy; the cost of recovery from a major incident almost always exceeds the cost of prevention.</p>

<h2>2. What Are Our Biggest Cybersecurity Risks, and How Are We Mitigating Them?</h2>

<p>Cybersecurity risks come from multiple sources: external attackers, supply chain compromises, human error, and increasingly, the AI systems your organization is deploying. The board needs visibility into which risks are most material to the business and what strategies are in place to address them.</p>

<p>Request regular risk summaries from your CISO that include not just identified threats but their potential business impact. A sophisticated ransomware attack does not just encrypt systems; it halts operations, damages customer trust, triggers regulatory investigations, and exposes the organization to litigation. Make sure risk assessments connect technical vulnerabilities to business consequences.</p>

<p>Pay particular attention to third-party risk. Most organizations rely on dozens or hundreds of vendors for critical services--cloud providers, payroll systems, customer relationship management platforms. Each represents a potential entry point for attackers. Ask how your organization assesses vendor security and whether you have visibility into their security postures, not just their assurances.</p>

<h2>3. How Much Are We Spending and Is It Sufficient?</h2>

<p>Cybersecurity spending is often opaque to boards. You may see a total IT security budget without understanding whether it covers the right things. Ask for breakdowns: how much goes to prevention versus detection versus response? What is the investment in security awareness training? How much is allocated to technology refresh versus maintaining legacy systems?</p>

<p>Legacy systems deserve particular attention. Many organizations continue to rely on outdated technology that vendors no longer support. In January 2023, Cisco warned of critical vulnerabilities affecting end-of-life routers, equipment last sold in 2020, with no patches forthcoming. These systems cannot be fully secured. Your organization should have a clear roadmap for retiring or replacing legacy infrastructure, with realistic timelines and budgets.</p>

<h2>4. Do We Have a Tested Incident Response Plan?</h2>

<p>Despite best efforts, breaches happen. The question is not whether your organization will face a cybersecurity incident, but whether you are prepared to respond effectively. Your incident response plan should be a living document, not a binder gathering dust.</p>

<p>The board has specific responsibilities during a crisis. You may need to decide whether to pay a ransom, my advice is almost always no, unless in truly exceptional circumstances with no alternative recovery path. You will need to liaise with major customers who may be affected. You must be available for emergency consultations with executives as the situation develops.</p>

<p>These decisions cannot be made in the moment without preparation. Insist on tabletop exercises that simulate major incidents. These exercises reveal gaps in coordination, clarify decision rights, and ensure that when a real crisis occurs, your team knows how to execute rather than improvise.</p>

<h2>5. Are We Compliant With Evolving Regulations and How Are We Monitoring Changes?</h2>

<p>The regulatory landscape has become significantly more complex. Beyond sector-specific requirements, organizations now face cross-cutting obligations: NIS2 for critical infrastructure and important entities across the EU; DORA for financial services; SEC disclosure rules for public companies in the U.S.; and AI governance frameworks and regulations.</p>

<p>Your organization needs processes to monitor regulatory developments and assess their applicability. This is not a set-and-forget exercise. Regulations change, enforcement priorities shift, and what was optional yesterday may be mandatory tomorrow. Ensure you have access to qualified legal and cybersecurity expertise to interpret these requirements for your board.</p>

<h2>Building the Right Structure</h2>

<p>Effective oversight requires the right committee structures. There is no single best approach, but several models work:</p>

<ul><li><strong>Governance and risk committees</strong> can oversee cybersecurity as part of broader risk management responsibilities</li><li><strong>Audit committees</strong> can review whether security policies align with standards and best practices</li><li><strong>Dedicated cybersecurity committees</strong> provide focused attention, typically led by the CISO with representation from IT, legal, and human resources</li><li><strong>Technology committees</strong> ensure security considerations are embedded in technology strategy and investment decisions</li></ul>

<p>The trend is toward greater board access to cybersecurity expertise. Whether through a dedicated committee chair, an independent advisor, or board education programs, directors need independent sources of insight, not just management's perspective.</p>

<h2>Culture Is the Foundation</h2>

<p>Ultimately, technology and processes matter less than culture. As I have written before, a strong cybersecurity culture requires four elements: commitment from leadership, obsession with prevention, collaboration across departments, and willingness to learn from mistakes.</p>

<p>This culture starts with the board. When directors treat cybersecurity as a strategic priority, ask probing questions, and hold management accountable for addressing gaps, they signal that security is everyone's responsibility. When boards treat it as a technical matter to be delegated, they create blind spots that attackers exploit.</p>

<p>The board's cyber agenda has indeed changed. The directors who adapt, who develop fluency in risk, who ensure their organizations are resilient, who treat cybersecurity as a governance imperative, will protect not just their organizations, but their own positions. Those who do not risk learning the hard way that in 2026, cybersecurity failure is board-level failure.</p>

<p><em>Published March 25, 2026 | Originally appeared in modified form in "The Book on Cybersecurity" (2023)</em></p>
    `,
  },
  {
    slug: "shadow-ai-guide-2026",
    title: "Shadow AI: What to Do in 2026",
    subtitle: "A practical guide to discovering and governing unsanctioned AI use in your organization",
    date: "2026-03-25",
    dateFormatted: "March 25, 2026",
    category: "AI Governance",
    tags: ["Shadow ai","Ai governance","Eu ai act","Risk management","Compliance"],
    readingTime: "8 min read",
    featured: true,
    heroImage: "/images/articles/shadow-ai-guide-2026.jpg",
    linkedinUrl: "https://www.linkedin.com/pulse/shadow-ai-what-do-2026-arnaud-wiehe-xllwe",
    author: "Arnaud Wiehe",
    authorBio: "Author of 'The Book on Cybersecurity' and 'Emerging Tech, Emerging Threats'. Advisor to boards on AI governance and digital risk.",
    excerpt: "In 2023, Samsung employees inadvertently uploaded sensitive information to ChatGPT—becoming the most cited example of shadow AI. With 28% of employees now using unapproved AI tools at work, organizations need a Shadow AI Discovery and Response Programme. The EU AI Act now imposes fines up to €15 million for deploying high-risk AI without proper governance.",
    content: `
<p>In 2023, Samsung Electronics made headlines when employees inadvertently uploaded sensitive information to ChatGPT, including proprietary source code and internal meeting notes. Samsung's response was immediate: they banned consumer AI tools while building controlled internal alternatives. This became the most widely cited example of what we now call <strong>shadow AI</strong>.</p>

<p>Shadow AI is artificial intelligence used within an organization without the knowledge, approval, or oversight of IT, legal, compliance, or governance functions. It is the AI equivalent of shadow IT—but with risks that shadow IT never carried.</p>

<h2>The Scale of Shadow AI</h2>

<p>A 2024 survey by Salesforce found that 28% of employees were using AI tools at work that had not been approved by their employer. Among knowledge workers, that figure was significantly higher. The tools range from well-known consumer platforms to dozens of specialist AI productivity tools covering writing, research, legal review, image generation, and code assistance.</p>

<h2>Categories of Risk</h2>

<p>Shadow AI presents several distinct categories of risk:</p>

<p><strong>Data Exposure</strong>: When employees use consumer-grade AI tools, the data they input—customer names, contract terms, financial projections, personal information—may be used to train the model or stored on third-party servers.</p>

<p><strong>Output Reliance</strong>: Employees acting on AI-generated outputs that have not been validated, particularly in areas like legal research or financial modeling, where an authoritative-sounding hallucination can cause serious harm.</p>

<p><strong>Accountability Opacity</strong>: When something goes wrong with a shadow AI output, there is no audit trail, no approved use case documentation, and no clear owner.</p>

<h2>The EU AI Act Dimension</h2>

<p>The European Union's AI Act, which entered into force in August 2024, creates legal obligations that make shadow AI a compliance issue. Organizations deploying high-risk AI systems without proper governance face fines of up to €15 million or 3% of global annual turnover.</p>

<h2>Practical Response: Discovery and Channeling</h2>

<p>Blanket bans, as Samsung's experience suggests, are temporary measures at best. The more durable solution is a Shadow AI Discovery and Response Programme:</p>

<p>1. <strong>Technology Scanning</strong>: Identify unauthorized AI tool usage on corporate networks 2. <strong>Policy Clarity</strong>: Create an AI Acceptable Use Policy that is visible, understandable, and fair 3. <strong>Sanctioned Pathway</strong>: Enable employees to request evaluation and approval of tools they want to use</p>

<p>The tone matters enormously. Employees who fear punishment for honest answers will not give them.</p>

<h2>Assessment: Where Is Your Organization?</h2>

<p>The first step is understanding your current state. Ask these questions:</p>

<ul><li>Can you name the AI systems currently in use across your organization?</li><li>Do you have visibility into generative AI usage by employees?</li><li>Is there an AI Acceptable Use Policy communicated to staff?</li><li>Have you assessed your AI systems against the EU AI Act risk tiers?</li></ul>

<p>Organizations that cannot answer these questions confidently have a shadow AI governance gap that requires immediate attention.</p>

<p><em>Published on LinkedIn, March 25, 2026</em></p>
    `,
  },
  {
    slug: "year-of-autonomous-agents",
    title: "The Year of Autonomous Agents",
    subtitle: "Why 2026 feels like the inflection point for agent security and governance",
    date: "2026-03-22",
    dateFormatted: "March 22, 2026",
    category: "AI Governance",
    tags: ["Autonomous Agents","Openclaw","AI Governance","Agent Security","Emerging Tech"],
    readingTime: "4 min read",
    featured: false,
    heroImage: "/images/articles/year-of-autonomous-agents.png",
    linkedinUrl: "",
    author: "Arnaud",
    authorBio: "Author of 'Emerging Tech, Emerging Threats' and 'AI Governance Guide'. Building ClawBlade.ai - security tools for OpenClaw users.",
    excerpt: "Autonomous agents change the security model fundamentally. Why 2026 feels like an inflection point for AI governance, accountability, and agent security.",
    content: `
<p>AI in 2026: This time feels different</p>

<p>I've been experimenting with autonomous AI agents, specifically OpenClaw (an open-source local agent framework), for the past few weeks. Not reading about it, but actually running it, breaking it, and watching it do unexpected things.</p>

<p>It has changed how I think about AI risk.</p>

<p>For a while, the conversation has focussed on Large Language Models as assistants: copilots, chatbots, tools that respond to prompts. You ask, it answers. Humans stay in the loop. The risk surface is manageable.</p>

<p>Autonomous agents are different. When I started using OpenClaw locally, connecting it to tools and personal workflows, the productivity upside was immediately obvious. It doesn't just generate responses. It executes tasks, maintains memory, interacts with applications, and keeps working without constant prompting. Full transparency though, it requires significant tinkering to keep running smoothly.</p>

<p>What made the risk concrete for me, was watching it design and build a Mission Control GUI I hadn't fully scoped. It wasn't perfect, but it created what it thought I wanted. In that moment I felt nervous about the power I'd handed it, like credentials, file access, internet access, live APIs...and it was making decisions. I had deliberately constrained its permissions before starting like read-only access to sensitive directories, no outbound calls without explicit approval. That containment gave me some comfort. But it made me ask how many organisations deploying agents have thought this through with the same rigour.</p>

<p>Most are probably still using the copilot playbook. They're evaluating autonomous agents the way they evaluated AI assistants, as productivity tools with a data privacy angle. GDPR compliance, API security, the usual checklist.</p>

<p>But none of that addresses the harder problem.</p>

<p>The harder problem is that we are giving AI not just intelligence, but genuine agency like the ability to act, execute, and interact with systems, often with privileges that previously required human sign-off. That changes the security model fundamentally.</p>

<p>Of the risks this introduces, prompt injection is the most underappreciated. Malicious input that manipulates an agent into unintended actions isn't theoretical, it's an active attack surface that most governance frameworks weren't designed to cover. Beyond that, accountability becomes genuinely complex. If an agent makes a bad call mid-workflow, who owns it? How do you intervene quickly enough? How do you govern agent-to-agent interactions when chains of delegation obscure the original intent?</p>

<p>These aren't future-roadmap questions. Enterprises are hitting them right now. The organisations getting this right are treating autonomous agents less like software and more like a new category of employee with scoped permissions, audit trails, intervention mechanisms, clear lines of accountability. That framing sounds obvious stated plainly. In practice, almost nobody has operationalised it yet and the gap between obvious and implemented is where the real risk lives.</p>

<p>We're genuinely early.</p>

<p>The tooling is immature, governance frameworks don't fit, and most teams are still in the "let's see what this can do" phase. That's how new paradigms start, but the window to build good habits is now, before agents are embedded in critical workflows and retrofitting governance becomes far more costly.</p>

<p>I'm curious what others are seeing. Are you treating autonomous agents differently from other AI deployments from a security and governance perspective, or are you still running the same playbook?</p>
    `,
  },
  {
    slug: "openclaw-security-crisis-5-cves-2026",
    title: "5 CVEs in 7 Days: The OpenClaw Security Crisis Is Here",
    subtitle: "When China's Government Warns About AI Agent Security, the Industry Should Listen",
    date: "2026-03-20",
    dateFormatted: "March 20, 2026",
    category: "Cybersecurity",
    tags: ["Openclaw","CVE","Security","AI Agents","Cybersecurity","Vulnerability","China Cybersecurity","Emerging Tech"],
    readingTime: "5 min read",
    featured: true,
    heroImage: "/images/articles/openclaw-security-crisis.png",
    linkedinUrl: "",
    author: "Arnaud",
    authorBio: "Author of 'Emerging Tech, Emerging Threats' and 'AI Governance Guide'. Building ClawBlade.ai - Security tools for OpenClaw.",
    excerpt: "The shift to agentic computing has begun, but security is still DIY. This week, five new vulnerabilities dropped for OpenClaw — five ways your AI agent can be turned against you. Just like early web commerce needed SSL and fraud protection to become mainstream, AI agents need security to achieve widespread adoption. Here's why early adopters must roll their own security — and what that means for leaders deploying OpenClaw today.",
    content: `
<p>The Shift to Agentic Computing Has Begun, But Security Is Still DIY</p>

<p>In the early days of the Internet, people were terrified of buying stuff online. Not because they didn't want stuff. We all want more stuff, but people were terrified of typing their credit card number into a browser.</p>

<p>"What if someone steals it?" "What if the site isn't real?" "What if the internet is just a fad?"</p>

<p>Remember those days?</p>

<p>My current obsession is Agentic AI, specifically OpenClaw.</p>

<p>This week, five new vulnerabilities were dropped for OpenClaw. That's five ways your AI agent can be turned against you. In seven days.</p>

<p>My view is that technology doesn't achieve mainstream adoption until it's secure enough for ordinary people to trust it.</p>

<p>Credit cards on the internet didn't explode because people suddenly loved typing in 16-digit numbers. They exploded because SSL, fraud protection, and chargeback mechanisms made it safe enough.</p>

<p>The technology worked and security made it adoptable.</p>

<p>I think the same security-adoption challenges plague the autonomous vehicle and humanoid robotics industries currently. OpenClaw and agentic AI is at that same inflection point.</p>

<p>The technology works. 250K+ GitHub stars, making it one of the most successful open source projects ever. The shift to agentic computing has clearly begun.</p>

<p>But the security? That's still DIY. If your DIY skills are anything like mine, you'll know that DIY is not usually professional enough. What makes this even more challenging is that OpenClaw's attack surface is vast: third-party skills with unknown provenance, credentials floating in environment variables, network services listening where they shouldn't, sandboxes that aren't as isolated as we think.</p>

<p>The uncomfortable truth though is that we're in the early adopter phase of agentic computing, and early adopters have always had to roll their own security and take on greater risks.</p>

<p>The credit card companies didn't build fraud detection overnight. Early web merchants wrote their own encryption. The infrastructure we take for granted today was built by people who couldn't wait for it to exist.</p>

<p>What this means for leaders:</p>

<p>If you're deploying OpenClaw (or any AI agent framework) today, security isn't a feature you can defer. It's a prerequisite.</p>

<p>The shift to agentic computing has begun. That part isn't a prediction anymore — it's a headline.</p>

<p>What comes next depends on what we do in the next 12 months. Audit your agent deployments. Treat third-party skills like untrusted code. Isolate your instances. Build governance before you need it.</p>

<p>Credit cards didn't survive the early chaos by accident. Fraud detection, SSL, chargebacks. Someone built all of that. Deliberately. Before the breach that would have ended it.</p>

<p>Be that person for your organization. The agents are already running. The question is whether you're running them, or they're running you.</p>
    `,
  },
  {
    slug: "openclaw-security-best-practices",
    title: "OpenClaw Security Best Practices: A Practical Guide",
    subtitle: "",
    date: "2026-03-18",
    dateFormatted: "March 18, 2026",
    category: "Cybersecurity",
    tags: ["Openclaw","Security","Best Practices","AI Agents"],
    readingTime: "5 min read",
    featured: false,
    heroImage: "/images/articles/openclaw-security-best-practices.png",
    linkedinUrl: "",
    author: "Arnaud",
    authorBio: "Author of “Emerging Tech, Emerging Threats” and “AI Governance Guide”.",
    excerpt: "Practical security best practices for OpenClaw deployments. Learn how to harden your AI agent setup with actionable tips for credentials, network security, and configuration management.",
    content: `
<p>If you read my last article, you know I've been running OpenClaw, the open-source autonomous AI agent, as a personal AI experiment. As an AI and Cybersecurity professional and author of a book on securing Emerging Technologies, it should come as no surprise to anyone. My OpenClaw can access files, runs on a schedule, briefs me in the morning, and remembers who I am, based on what I tell it. But being ultra paranoid about security, I decided to research and build what I can only describe as a full digital airlock.</p>

<h2>First, some context on why this matters right now</h2>

<p>OpenClaw went from niche developer experiment to global conversation piece almost overnight. This week at Nvidia's GTC 2026 conference, the annual event that has become something of a Super Bowl for the AI industry, Jensen Huang stood on stage and declared that OpenClaw is the "operating system for personal AI" and compared it to the importance of the Mac and Windows operating systems.</p>

<p>He didn't stop there. "Every company in the world today needs to have an OpenClaw strategy, an agentic system strategy. This is the new computer," Huang said. "This is as big of a deal as HTML, as big of a deal as Linux."</p>

<p>Nvidia also launched NemoClaw, an enterprise-grade wrapper built on OpenClaw and Huang worked directly with OpenClaw creator Peter Steinberger to build it, shouting him out during the keynote.</p>

<p>When the world's most valuable technology company builds its flagship enterprise AI product on top of an open-source tool, and its CEO calls it the most significant software development in a generation, I pay attention.</p>

<p>While I was keenly following the hype, I was also painfully aware of the security risks and some of the unfortunate stories of early victims.</p>

<h2>The fear was legitimate</h2>

<p>Most articles I found about OpenClaw eventually arrived at the same place: this thing is powerful, and if you're not careful, it's dangerous.</p>

<p>An AI agent that can read your emails, execute terminal commands, manage your calendar, and message people on your behalf isn't just a productivity tool. It's a persistent process with elevated access to your digital life. And unlike a chatbot, it doesn't wait to be asked. It acts.</p>

<p>The attack surface is real. Prompt injection, where malicious instructions get embedded inside a document, email, or web page the agent processes, can cause it to execute actions you never intended. The ClawHub skill marketplace has had serious issues with malicious third-party skills. And most people deploying OpenClaw out of the box had done little to nothing to harden it.</p>

<p>I wasn't willing to accept that. So before I ran the agent, I built the environment.</p>

<h2>The airlock: what I actually set up</h2>

<p>I want to be specific here, because vague advice about "being careful with AI" is not useful.</p>

<p><strong>I started with dedicated hardware.</strong> A separate machine with 24GB RAM and 1TB of storage, purchased specifically for this. Not my work laptop. Not my personal machine. A clean device with no prior history, no existing accounts, no shared credentials.</p>

<p><strong>Then a separate network.</strong> The OpenClaw machine sits on its own isolated network, physically separated from the environment I use for work and daily life. If something goes wrong, a prompt injection, a rogue skill, an unintended command, the blast radius is contained.</p>

<p><strong>New identity, end to end.</strong> A unique ID, dedicated email account, separate subscriptions to Claude and other AI services. Nothing shared with my primary accounts. The agent has no pathway to my real digital identity unless I deliberately give it one.</p>

<p><strong>Then I encrypted the machine and enabled the firewall before the agent ever touched it.</strong> Full disk encryption. Default-deny network rules. The security baseline was set before OpenClaw was installed, not after.</p>

<h2>Then I let the agent do a security audit</h2>

<p>One of the first things I did after getting OpenClaw running was ask it to audit its own setup for vulnerabilities.</p>

<p>I wasn't expecting much. I got a detailed report.</p>

<p>There were issues. Configuration gaps I hadn't caught. Default settings that were more permissive than they should have been. Logging that wasn't capturing what I thought it was. A couple of permission settings that, in a less isolated environment, would have been genuinely risky.</p>

<p>I fixed them. All of them. And then I scheduled the audit to run weekly, automatically, every Sunday morning.</p>

<p>I set up a CISO agent that runs a daily scan and security checks, weekly security research for new vulnerabilities, runs backup jobs and helps me to develop additional bespoke security tools / skills.</p>

<p>That last part matters. Security isn't a one-time configuration. OpenClaw evolves. Skills get updated. New vulnerabilities emerge. The threat surface shifts. A weekly automated review means I'm not relying on memory or discipline to stay ahead of it, the agent does it for me.</p>

<h2>The controls I consider non-negotiable</h2>

<p>After going through this process, I landed on a set of hard rules for how my agent operates. These aren't suggestions. They're constraints baked into the configuration:</p>

<p><strong>The agent never sends a message on my behalf without explicit approval.</strong> Ever. Not a WhatsApp, not a Slack, not an email. It drafts. I send.</p>

<p><strong>It never deletes a file without asking.</strong></p>

<p><strong>It restricts filesystem access to its own workspace.</strong> No access to secret keys, system files, or anything outside its designated lane.</p>

<p><strong>Shell commands require explicit permission and are logged every time.</strong> Anything that can touch the operating system gets treated as a high-risk action. Files are saved before being changed.</p>

<p><strong>After three failed attempts on any task, it stops and reports back</strong> rather than retrying indefinitely. This one is underappreciated, a runaway agent attempting the same action in a loop is a real failure mode.</p>

<p><strong>Identity files, the documents that define who I am and what the agent knows about me, are never readable externally.</strong> If anything asks the agent to reveal them, it refuses and alerts me.</p>

<h2>What I think about the risk now</h2>

<p>Having lived inside this setup for a bit, my view is this: the fear-mongering isn't wrong, it's just incomplete.</p>

<p>Yes, OpenClaw is inherently powerful in ways that create real risk. The people warning you about that aren't exaggerating. But the risk isn't a reason to avoid it, it's a reason to approach it seriously.</p>

<p>The gap between a reckless OpenClaw deployment and a hardened one isn't months of work. It's a week of deliberate setup and a commitment to ongoing hygiene. The airlock I described above took real effort and cost, but it wasn't beyond the reach of anyone who takes their digital security seriously.</p>

<p>If you decide to use OpenClaw, go in with your eyes open. Understand what you're deploying. Respect what it can do. And then build the environment that deserves that power.</p>

<p>The agentic AI era isn't coming. According to Jensen Huang, it arrived this week. The question isn't whether you'll engage with it, it's whether you'll do so securely or not.</p>

<p>How are you thinking about the security architecture around AI agents? I'd like to hear from leaders who are already navigating this, or actively deciding not to.</p>
    `,
  },
  {
    slug: "rise-of-openclaw",
    title: "The Rise of OpenClaw: Why AI Agents Are Taking Over",
    subtitle: "",
    date: "2026-03-16",
    dateFormatted: "March 16, 2026",
    category: "Industry Trends",
    tags: ["Openclaw","AI Agents","Trends","Emerging Tech"],
    readingTime: "5 min read",
    featured: false,
    heroImage: "/images/articles/rise-of-openclaw.png",
    linkedinUrl: "",
    author: "Arnaud",
    authorBio: "Author of “Emerging Tech, Emerging Threats” and “AI Governance Guide”.",
    excerpt: "OpenClaw is the fastest-growing AI agent framework. Here's why developers are flocking to it and what it means for the future of work, automation, and human-AI collaboration.",
    content: `
<p>By now, you may have heard the name. If not, let me catch you up.</p>

<p>OpenClaw is a free, open-source autonomous AI agent created by Austrian developer Peter Steinberger. Unlike chatbots that simply respond to queries, OpenClaw executes real-world tasks like researching topics, developing code, reading emails, managing calendars, running terminal commands, and maintaining memory across sessions. It runs as a local service on your own machine, or cloud based virtual machine, and connects to the chat apps you already use, like WhatsApp, Telegram, Slack, Discord, and more.</p>

<p>Think of it as an always on personal AI chief of staff. One that actually remembers you and works for you.</p>

<p>Most AI assistants forget you the moment you close the tab.</p>

<p>Mine doesn't.</p>

<p>I've been running my own personal AI agent, powered by OpenClaw, operating autonomously via scheduled "heartbeats" and delivering a morning briefing on what it did while I slept. It knows:</p>

<ul><li>Who I am</li><li>What I care about</li><li>What I'm working on</li><li>What happened yesterday</li></ul>

<p>Not because I told it again. Because it remembers.</p>

<p>Here's what that looks like in practice:</p>

<p><strong>It reads my files, not just my prompts.</strong> My projects, priorities, and preferences live in a structured workspace. The agent reads them at startup. No re-explaining who I am every session.</p>

<p><strong>It takes initiative, within limits I define.</strong> Morning intelligence briefs. Calendar reminders. Proactive research on AI governance, cybersecurity, and emerging tech. It doesn't wait to be asked.</p>

<p><strong>It runs on my machine.</strong> No third-party cloud storing my notes, emails, or private context. I built a dedicated, air-gapped laptop on a separate network — unique usernames, emails, and passwords, isolated from my daily systems. Local-first by design.</p>

<p><strong>It gets smarter over time.</strong> Every session adds to persistent memory files. The agent distills what matters and updates its long-term knowledge base. No starting from scratch.</p>

<p>This isn't the future. I'm using it today.</p>

<p>Now for the honest part: The cons.</p>

<p>I strongly recommend exploring OpenClaw, but I'll be direct: most people won't run it successfully. Here's why:</p>

<p><strong>Cost.</strong> You need your own LLM API keys (Claude, GPT, DeepSeek). Those API calls accumulate. The software itself is free, but you bring your own API keys, and usage costs add up for always-on agents. You can run free open source LLMS (Qwen, Kimi-K2, Deepseek) but they require significant, expensive hardware resources to run.</p>

<p><strong>Complexity.</strong> Installation requires setting it up on a server or local device and connecting it to a language model a process that can be challenging for less technical users.</p>

<p><strong>Security exposure.</strong> This is the big one, and it deserves its own article, which I'm writing next. For now, know that Openclaw is inherently insecure because it can access email accounts, calendars, messaging platforms, and system-level commands, it exposes users to real security vulnerabilities. Prompt injection attacks, where malicious instructions are embedded in emails, documents, or web pages the agent processes can cause it to execute unintended actions.</p>

<p>In OpenClaw, Skills are modular add-ons installable from ClawHub, the public skill marketplace, which dramatically expand what your agent can do, but they represent a serious attack surface. Security researchers have identified hundreds of malicious skills in the registry, with some estimates placing the infection rate at around 20% of all published skills. ClawHub now displays a security scan for each skill, combining a VirusTotal verdict with OpenClaw's own confidence indicator. But even a "Benign / High Confidence" result is no guarantee, and you should treat any third-party skill as untrusted code until you've reviewed it yourself.</p>

<p>My mitigation: a dedicated standalone laptop, a fully separated network, isolated accounts, and strict controls over what the agent can and cannot touch. This isn't plug-and-play. It's a deliberate security architecture.</p>

<p>I'll be publishing a detailed breakdown of how I secured my OpenClaw setup in my next article.</p>

<p><strong>What comes next: The competitive landscape</strong></p>

<p>OpenClaw's rise has not gone unnoticed by the major players.</p>

<p>In February 2026, creator Peter Steinberger announced he would be joining OpenAI, with the project moving to an independent open-source foundation sponsored and supported by OpenAI. The model is MIT licensed, free to use, modify, and build on commercially. Interestingly, OpenClaw went through two prior name changes. It was originally called Clawdbot, then Moltbot. The first after Anthropic threatened legal action over the name's similarity to Claude, and the second because Steinberger simply preferred the new name.</p>

<p>Meanwhile, Nvidia is making its move. Nvidia is planning to launch an open-source enterprise-focused AI agent platform called NemoClaw, and has reportedly begun pitching it to companies including Salesforce, Cisco, Google, Adobe, and CrowdStrike.</p>

<p>Nvidia CEO Jensen Huang has called OpenClaw "single most important release of software probably ever" Whether or not that holds, the agentic AI era is no longer theoretical.</p>

<p>The gap between "AI I chat with" and "AI that actually knows me and acts on my behalf" is smaller than most people think and it's closing fast.</p>

<p>Have you tried building a persistent AI agent? What's your setup, and how are you thinking about the security tradeoffs?</p>

<ul><li><strong>Published:</strong> 2026-03-16</li><li><strong>Platform:</strong> LinkedIn</li><li><strong>Engagement:</strong> <em>(To be updated)</em></li><li><strong>Follow-up post:</strong> ClawBot Security Checklist (in progress)</li></ul>

<ul><li>Next: ClawBot Security Checklist (draft in progress)</li><li>Series: OpenClaw Deep Dive</li></ul>
    `,
  }
]
